[package]
name = "rust-dnn-nn"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "*"

[features]
default = []
cuda = ["rust-dnn-core/cuda"] 

[dependencies.rust-dnn-core]
path = "../rust-dnn-core"
